package com.banco.co.auditLog.enums;

public enum AuditAction {

    // Usuario
    CREATE_PROFILE,
    UPDATE_PROFILE,
    DELETE_PROFILE,
    CREATE_PROFILE_FAILED,
    UPDATE_PROFILE_FAILED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_CHANGE_FAILED,
    EMPLOYEE_CREATED,
    USER_READ_BY_ADMIN,
    USER_UPDATED_BY_ADMIN,
    USER_SUSPENDED,
    USER_ACTIVATED,
    USER_STATUS_CHANGED,

    // Cuenta
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_CLOSED,

    // Transacción
    TRANSACTION_CREATED,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,

    // Tarjeta
    CARD_CREATED,
    CARD_ACTIVATED,
    CARD_BLOCKED,

    // Seguridad
    UNAUTHORIZED_ACCESS,
    FRAUD_DETECTED,
    SUSPICIOUS_ACTIVITY
}
