package com.banco.co.auditLog.enums;

public enum AuditAction {

    // Usuario
    CREATE_PROFILE,
    UPDATE_PROFILE,
    DELETE_PROFILE,
    CREATE_PROFILE_FAILED,
    UPDATE_PROFILE_FAILED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_CHANGE_FAILED,
    EMPLOYEE_CREATED,
    USER_READ_BY_ADMIN,
    USER_UPDATED_BY_ADMIN,
    USER_SUSPENDED,
    USER_ACTIVATED,
    USER_STATUS_CHANGED,

    // Cuenta
    ACCOUNT_CREATED,
    ACCOUNT_CREATED_FAILED,
    ACCOUNT_UPDATED,
    ACCOUNT_STATUS_CHANGED,
    ACCOUNT_STATUS_CHANGED_FAILED,
    ACCOUNT_READ,
    ACCOUNT_CLOSED,
    ACCOUNT_DELETED,
    ACCOUNT_DELETED_FAILED,
    ACCOUNT_CLOSED_BY_ADMIN,

    // Transacción
    TRANSACTION_CREATED,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,

    // Tarjeta
    CARD_CREATED,
    CARD_ACTIVATED,
    CARD_BLOCKED,
    CARD_CLOSED,
    CARD_LOST_REPORTED,
    CARD_STOLEN_REPORTED,
    CARD_LIMITS_UPDATED,
    CARD_FEATURES_UPDATED,
    CARD_STATUS_CHANGED,
    CARD_PIN_RESET,
    CARD_CREATED_FAILED,
    CARD_ACTIVATED_FAILED,
    CARD_BLOCKED_FAILED,
    CARD_READ,

    // Seguridad
    UNAUTHORIZED_ACCESS,
    FRAUD_DETECTED,
    SUSPICIOUS_ACTIVITY,



    // Envelopes
    ENVELOPE_CREATED,
    ENVELOPE_UPDATED,
    ENVELOPE_READ,
    ENVELOPE_DELETED,
    ENVELOPE_STATUS_CHANGED,
    ENVELOPE_DEPOSIT,
    ENVELOPE_WITHDRAWAL,
    ENVELOPE_CLOSED,
    ENVELOPE_GOAL_REACHED,
    ENVELOPE_AUTO_CONTRIBUTION_PROCESSED,
    ENVELOPE_AUTO_CONTRIBUTION_FAILED,

    // Notification
    EMAIL_SENT,
    EMAIL_DELIVERY_DEAD,
    EMAIL_ENQUEUE_DEDUPED
}
