ALTER TABLE permissions
    MODIFY COLUMN name        VARCHAR(100) NOT NULL,
    MODIFY COLUMN scope       VARCHAR(50)  NOT NULL,
    MODIFY COLUMN resource    VARCHAR(50)  NOT NULL,
    MODIFY COLUMN action      VARCHAR(50)  NOT NULL,
    MODIFY COLUMN description VARCHAR(200) NOT NULL;
